# 显示得workflow名称
name: GitHub Actions
on: 
  # 推送到main分支开始打包
  push:
    branches:
      - main

jobs:
  # 开始打包
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15]

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2.2.4
      with:
        version: 7
    - name: Use Node.js 18.12.1
      uses: actions/setup-node@v3
      with:
        node-version: 18.12.1
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install && pnpm build

    - name: deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        branch: gh-pages
        folder: build   # build后文件目录